### ISSUE TITLE
Deposit and profile error

### ISSUE THREAD

**Issue by septk** [popmanhe/Node_Dice#4] opened 2017-06-20 20:15 UTC
Failed to load resource: the server responded with a status of 404 (Not Found) deposit and profile when I sign up.

Thanks for your support :)

**Comment by popmanhe** [comment] 2017-06-20 20:25
Please provide more info on this issue. Coin deposit and address won't work because you need a actual running btc client to do it. But it can be easily done by yourself. There is help class in the project. Modify that file and suit your needs.

**Comment by septk** [comment] 2017-07-07 09:54
If you try your demo, you have same error than me. Try to sign up with a new user.!

@popmanhe thanks!

**Comment by popmanhe** [comment] 2017-10-28 21:42
@septk 
Sorry for the late reply. I have been busy with other projects.  The issue is fixed now. You can try it again on the web site.

**Closed as completed by popmanhe** 2017-10-28 21:42 UTC
